//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<DSS.Data.Models.Entities.Schedule>
    {
    	
    			public virtual int ScheduleID { get; set; }
    			public virtual int DeviceID { get; set; }
    			public virtual int ScenarioID { get; set; }
    			public virtual int TimeFilter { get; set; }
    			public virtual int LayoutID { get; set; }
    			public virtual int Priority { get; set; }
    			public virtual int DayFilter { get; set; }
    	
    	public ScheduleViewModel() : base() { }
    	public ScheduleViewModel(DSS.Data.Models.Entities.Schedule entity) : base(entity) { }
    
    }
}
