//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualTypeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<DSS.Data.Models.Entities.VisualType>
    {
    	
    			public virtual int VisualTypeID { get; set; }
    			public virtual string TypeName { get; set; }
    	
    	public VisualTypeViewModel() : base() { }
    	public VisualTypeViewModel(DSS.Data.Models.Entities.VisualType entity) : base(entity) { }
    
    }
}
