//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSS.ResourcesLanguage.GeneralError", typeof(GeneralError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box is being in used.
        /// </summary>
        public static string BoxInUse {
            get {
                return ResourceManager.GetString("BoxInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter box name.
        /// </summary>
        public static string BoxName {
            get {
                return ResourceManager.GetString("BoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this box.
        /// </summary>
        public static string BoxRecover {
            get {
                return ResourceManager.GetString("BoxRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this brand.
        /// </summary>
        public static string BrandRecover {
            get {
                return ResourceManager.GetString("BrandRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your brand is safe :).
        /// </summary>
        public static string BrandSafe {
            get {
                return ResourceManager.GetString("BrandSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled !.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not send request.
        /// </summary>
        public static string CantSentReq {
            get {
                return ResourceManager.GetString("CantSentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your box has been deleted.
        /// </summary>
        public static string DeleteBox {
            get {
                return ResourceManager.GetString("DeleteBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your brand has been deleted.
        /// </summary>
        public static string DeleteBrand {
            get {
                return ResourceManager.GetString("DeleteBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted !.
        /// </summary>
        public static string Deleted1 {
            get {
                return ResourceManager.GetString("Deleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has been deleted .
        /// </summary>
        public static string DeleteDevice {
            get {
                return ResourceManager.GetString("DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location has been deleted.
        /// </summary>
        public static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to manage content on this device.
        /// </summary>
        public static string DeleteNotif {
            get {
                return ResourceManager.GetString("DeleteNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your screen has been deleted.
        /// </summary>
        public static string DeleteScreen {
            get {
                return ResourceManager.GetString("DeleteScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter district.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured !.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is safe :).
        /// </summary>
        public static string Filesafe {
            get {
                return ResourceManager.GetString("Filesafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to delete it.
        /// </summary>
        public static string IfDelete {
            get {
                return ResourceManager.GetString("IfDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter duration.
        /// </summary>
        public static string ImgDuration {
            get {
                return ResourceManager.GetString("ImgDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input with format 00:00:00.
        /// </summary>
        public static string ImgFormat {
            get {
                return ResourceManager.GetString("ImgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is being used.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this location.
        /// </summary>
        public static string LocationRecover {
            get {
                return ResourceManager.GetString("LocationRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location is safe :).
        /// </summary>
        public static string LocationSafe {
            get {
                return ResourceManager.GetString("LocationSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to và nhấp tiếp theo.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, cancel it !.
        /// </summary>
        public static string NoCancel {
            get {
                return ResourceManager.GetString("NoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this file.
        /// </summary>
        public static string notbeable {
            get {
                return ResourceManager.GetString("notbeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check at least 1 day.
        /// </summary>
        public static string PleaseDay {
            get {
                return ResourceManager.GetString("PleaseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check at least 1 time.
        /// </summary>
        public static string PleaseTime {
            get {
                return ResourceManager.GetString("PleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select area !.
        /// </summary>
        public static string PlsArea {
            get {
                return ResourceManager.GetString("PlsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct error in step.
        /// </summary>
        public static string PlsCorrect {
            get {
                return ResourceManager.GetString("PlsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete playlist.
        /// </summary>
        public static string PlsDelete {
            get {
                return ResourceManager.GetString("PlsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete scenario.
        /// </summary>
        public static string PlsDeleteScen {
            get {
                return ResourceManager.GetString("PlsDeleteScen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose device.
        /// </summary>
        public static string PlsDev {
            get {
                return ResourceManager.GetString("PlsDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose scenario.
        /// </summary>
        public static string PlsScen {
            get {
                return ResourceManager.GetString("PlsScen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please detatch device.
        /// </summary>
        public static string PlsUnmatch {
            get {
                return ResourceManager.GetString("PlsUnmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your box is safe :).
        /// </summary>
        public static string SafeBox {
            get {
                return ResourceManager.GetString("SafeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is safe.
        /// </summary>
        public static string SafeDevice {
            get {
                return ResourceManager.GetString("SafeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your scenario is safe :).
        /// </summary>
        public static string SafeScen {
            get {
                return ResourceManager.GetString("SafeScen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your screen is safe :).
        /// </summary>
        public static string SafeScreen {
            get {
                return ResourceManager.GetString("SafeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your schedule has been deleted.
        /// </summary>
        public static string ScenDelete {
            get {
                return ResourceManager.GetString("ScenDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this scenario.
        /// </summary>
        public static string ScenRecover {
            get {
                return ResourceManager.GetString("ScenRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen is being used.
        /// </summary>
        public static string ScreenInUse {
            get {
                return ResourceManager.GetString("ScreenInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter screen name.
        /// </summary>
        public static string ScreenName {
            get {
                return ResourceManager.GetString("ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this screen.
        /// </summary>
        public static string ScreenRecover {
            get {
                return ResourceManager.GetString("ScreenRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose file to upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it !.
        /// </summary>
        public static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
