//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSS.ResourcesLanguage.GeneralError", typeof(GeneralError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled !.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not send request.
        /// </summary>
        public static string CantSentReq {
            get {
                return ResourceManager.GetString("CantSentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted !.
        /// </summary>
        public static string Deleted1 {
            get {
                return ResourceManager.GetString("Deleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured !.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is safe :).
        /// </summary>
        public static string Filesafe {
            get {
                return ResourceManager.GetString("Filesafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to delete it.
        /// </summary>
        public static string IfDelete {
            get {
                return ResourceManager.GetString("IfDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter duration.
        /// </summary>
        public static string ImgDuration {
            get {
                return ResourceManager.GetString("ImgDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input with format 00:00:00.
        /// </summary>
        public static string ImgFormat {
            get {
                return ResourceManager.GetString("ImgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is being used.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, cancel it !.
        /// </summary>
        public static string NoCancel {
            get {
                return ResourceManager.GetString("NoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to recover this file.
        /// </summary>
        public static string notbeable {
            get {
                return ResourceManager.GetString("notbeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete playlist.
        /// </summary>
        public static string PlsDelete {
            get {
                return ResourceManager.GetString("PlsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete scenario.
        /// </summary>
        public static string PlsDeleteScen {
            get {
                return ResourceManager.GetString("PlsDeleteScen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose file to upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it !.
        /// </summary>
        public static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
