//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScenarioAddForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioAddForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSS.ResourcesLanguage.ScenarioAddForm", typeof(ScenarioAddForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string LblDuration {
            get {
                return ResourceManager.GetString("LblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Scenario.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Scenario.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area&apos;s List Playlist.
        /// </summary>
        public static string TxtAreaListPlaylist {
            get {
                return ResourceManager.GetString("TxtAreaListPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Screen Layout.
        /// </summary>
        public static string TxtChooseScreenLayout {
            get {
                return ResourceManager.GetString("TxtChooseScreenLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Screen Type.
        /// </summary>
        public static string TxtChooseScreenType {
            get {
                return ResourceManager.GetString("TxtChooseScreenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Scenario Info.
        /// </summary>
        public static string TxtEnterScenarioInfo {
            get {
                return ResourceManager.GetString("TxtEnterScenarioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new scenario just following these simple steps.
        /// </summary>
        public static string TxtInfo {
            get {
                return ResourceManager.GetString("TxtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string TxtLandscape {
            get {
                return ResourceManager.GetString("TxtLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Scenario Details.
        /// </summary>
        public static string TxtNavigateScenarioDetails {
            get {
                return ResourceManager.GetString("TxtNavigateScenarioDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TxtNext {
            get {
                return ResourceManager.GetString("TxtNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Information.
        /// </summary>
        public static string TxtPlaylistInfo {
            get {
                return ResourceManager.GetString("TxtPlaylistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string TxtPortrait {
            get {
                return ResourceManager.GetString("TxtPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string TxtPreview {
            get {
                return ResourceManager.GetString("TxtPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string TxtPrevious {
            get {
                return ResourceManager.GetString("TxtPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string TxtPrivate {
            get {
                return ResourceManager.GetString("TxtPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string TxtPublic {
            get {
                return ResourceManager.GetString("TxtPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string TxtStep1 {
            get {
                return ResourceManager.GetString("TxtStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string TxtStep2 {
            get {
                return ResourceManager.GetString("TxtStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string TxtStep3 {
            get {
                return ResourceManager.GetString("TxtStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.
        /// </summary>
        public static string TxtStep4 {
            get {
                return ResourceManager.GetString("TxtStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step by Step.
        /// </summary>
        public static string TxtStepbyStep {
            get {
                return ResourceManager.GetString("TxtStepbyStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string TxtSubmit {
            get {
                return ResourceManager.GetString("TxtSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Playlist.
        /// </summary>
        public static string TxtYourPlaylist {
            get {
                return ResourceManager.GetString("TxtYourPlaylist", resourceCulture);
            }
        }
    }
}
