//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchedulingAddForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchedulingAddForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSS.ResourcesLanguage.SchedulingAddForm", typeof(SchedulingAddForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string BtnAuto {
            get {
                return ResourceManager.GetString("BtnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string BtnFixed {
            get {
                return ResourceManager.GetString("BtnFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset 123.
        /// </summary>
        public static string BtReset {
            get {
                return ResourceManager.GetString("BtReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string LblDeviceName {
            get {
                return ResourceManager.GetString("LblDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string LblEndtime {
            get {
                return ResourceManager.GetString("LblEndtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Mode.
        /// </summary>
        public static string LblPlaymode {
            get {
                return ResourceManager.GetString("LblPlaymode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Title.
        /// </summary>
        public static string LblScenarioTitle {
            get {
                return ResourceManager.GetString("LblScenarioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Orentation.
        /// </summary>
        public static string LblScreenOrentation {
            get {
                return ResourceManager.GetString("LblScreenOrentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string LblStarttime {
            get {
                return ResourceManager.GetString("LblStarttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time To Play.
        /// </summary>
        public static string LblTimetoPlay {
            get {
                return ResourceManager.GetString("LblTimetoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Schedule.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Device.
        /// </summary>
        public static string TxtDeviceNameDefault {
            get {
                return ResourceManager.GetString("TxtDeviceNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string TxtLandscape {
            get {
                return ResourceManager.GetString("TxtLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string TxtPortrait {
            get {
                return ResourceManager.GetString("TxtPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string TxtPrivate {
            get {
                return ResourceManager.GetString("TxtPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string TxtPublic {
            get {
                return ResourceManager.GetString("TxtPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Scenario.
        /// </summary>
        public static string TxtScenarioTitleDefault {
            get {
                return ResourceManager.GetString("TxtScenarioTitleDefault", resourceCulture);
            }
        }
    }
}
