//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int DeviceID { get; set; }
        public int ScenarioID { get; set; }
        public int LayoutID { get; set; }
        public int TimeFilter { get; set; }
        public int DayFilter { get; set; }
        public int Priority { get; set; }
        public bool isEnable { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
