//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;


    public partial interface IScheduleService : SkyWeb.DatVM.Data.IBaseService<Schedule>
    {
    }

    public partial class ScheduleService : SkyWeb.DatVM.Data.BaseService<Schedule>, IScheduleService
    {
        public ScheduleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IScheduleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
