//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ITimeSlotService : SkyWeb.DatVM.Data.IBaseService<TimeSlot>
    {
    }
    
    public partial class TimeSlotService : SkyWeb.DatVM.Data.BaseService<TimeSlot>, ITimeSlotService
    {
        public TimeSlotService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ITimeSlotRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
